// DROP8_REFACTOR_027_OPEN_ARENA_RECURRING_SUPPLY_DROPS
import { describe,expect,it } from 'vitest';import { readFileSync } from 'node:fs';import { resolve } from 'node:path';
const project=resolve(process.cwd(),'..');
const room=readFileSync(resolve(project,'server/src/rooms/Drop8Room.ts'),'utf8');
const world=readFileSync(resolve(project,'server/src/rooms/openArenaWorld.ts'),'utf8');
const notes=readFileSync(resolve(project,'docs/PATCH_NOTES.md'),'utf8');
describe('Refactor 027 Open Arena recurring supply drop source contract',()=>{
  it('is gated behind the 025A chain and respawn-mode update path',()=>{expect(room).toContain('DROP8_REFACTOR_025_OPEN_ARENA_KILL_LIMIT_MATCH_CYCLE');expect(room).toContain('DROP8_REFACTOR_027_OPEN_ARENA_RECURRING_SUPPLY_DROPS');expect(room).toContain("if(this.gameMode==='battleRoyale')this.updateZone(dt)");expect(room).toContain('if(this.arenaLike()){this.updateOpenArenaRespawns();this.updateOpenArenaWorld();this.broadcastOpenArenaScoreboard();}');expect(room).toContain("if(!this.arenaLike()||this.state.phase!=='ACTIVE'||this.openArenaRoundState!=='active')return");});
  it('keeps Battle Royale single-supply semantics while allowing bounded arena recurrence',()=>{expect(room).toContain('private activeSupplyDropCount()');expect(room).toContain('private spawnSupplyDrop(options:{allowMultiple?:boolean;openArenaRecurring?:boolean}={})');expect(room).toContain('if(!recurring&&this.state.supplySpawned)return false');expect(room).toContain('if(recurring&&this.activeSupplyDropCount()>=this.arenaMaxActiveSupplyDrops())return false');expect(room).toContain('if(!recurring)this.state.supplySpawned=true');expect(room).toContain('this.spawnSupplyDrop({allowMultiple:true,openArenaRecurring:true})');expect(room).toContain('this.spawnSupplyDrop();');});
  it('starts and restores the recurring timer across arena lifecycle boundaries',()=>{expect(room).toContain('private openArenaNextSupplyDropAt=0');expect(room.match(/this\.openArenaNextSupplyDropAt=this\.now\(\)\+this\.arenaSupplyFirstDelay\(\)/g)?.length).toBeGreaterThanOrEqual(2);expect(room).toContain('this.openArenaNextSupplyDropAt=0;this.openArenaNextRitualWarningAt=0;this.openArenaRitualActiveEndsAt=0;this.openArenaLastRitualPoint=null;for(const p of this.state.players.values())');expect(room).toContain('this.openArenaNextSupplyDropAt=now+(spawned?this.arenaSupplyInterval():this.arenaSupplyRetry())');});
  it('documents constants and avoids unrelated 029 feature markers after later feature patches',()=>{expect(world).toContain('OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS=60');expect(world).toContain('OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS=3');expect(notes).toContain('Refactor 027 — Open Arena Recurring Supply Drops');expect(room).not.toContain('DROP8_REFACTOR_029_ADHESIVE_FIRE_RATE_SUPPRESSION');});
});
