// DROP8_REFACTOR_015A_SUPPLY_DROP_FLAMETHROWER
import { describe, expect, it } from 'vitest';
import { FLAMETHROWER_BALANCE, MAP_CONFIGS, MOTORCYCLE_BALANCE, SUPPLY_DROP_BALANCE, WEAPONS, createSeededRandom, distance } from '@drop8/shared';
import { Drop8Room } from '../src/rooms/Drop8Room.js';
import { MotorcycleState, PlayerState, SupplyDropState } from '../src/rooms/schema.js';

function landedPlayer(id:string,x:number,y:number){const player=new PlayerState();player.id=id;player.phase='landed';player.alive=true;player.x=x;player.y=y;return player;}
function smallRoom(){const room=new Drop8Room() as any;room.state.mapId='small';room.state.mapSizeMode='small';room.state.worldSize=MAP_CONFIGS.small.width;room.state.zoneX=2048;room.state.zoneY=2048;room.state.zoneRadius=1900;return room;}
function armFlamethrower(player:PlayerState,fuel=100){player.primary='flamethrower';player.equipped='flamethrower';player.flamethrowerMagazine=fuel;player.angle=0;}

describe('Refactor 015A supply drop and flamethrower authority',()=>{
  it('triggers exactly once when the first zone begins shrinking',()=>{const room=smallRoom();const player=landedPlayer('zone-player',300,300);room.state.players.set(player.id,player);room.state.zoneStage=SUPPLY_DROP_BALANCE.triggerZoneStage;room.state.zoneState='WAITING';room.state.zoneTimer=.01;room.lootRandom=createSeededRandom(37);room.updateZone(.1);expect(room.state.zoneState).toBe('SHRINKING');expect(room.state.supplySpawned).toBe(true);expect(room.state.supplyDrops.size).toBe(1);room.updateZone(.1);expect(room.state.supplyDrops.size).toBe(1);});

  it('spawns one valid supply on every map',()=>{for(const mapId of ['small','large','dock8'] as const){const room=new Drop8Room() as any;room.state.mapId=mapId;room.state.mapSizeMode=mapId;room.state.worldSize=MAP_CONFIGS[mapId].width;room.state.zoneX=room.state.worldSize/2;room.state.zoneY=room.state.worldSize/2;room.state.zoneRadius=MAP_CONFIGS[mapId].initialZoneRadius;room.state.zoneStage=SUPPLY_DROP_BALANCE.triggerZoneStage;room.lootRandom=createSeededRandom(19);expect(room.spawnSupplyDrop()).toBe(true);expect(room.spawnSupplyDrop()).toBe(false);expect(room.state.supplyDrops.size).toBe(1);const drop=[...room.state.supplyDrops.values()][0]!;expect(drop.mapId).toBe(mapId);expect(drop.specialWeapon).toBe('flamethrower');expect(distance(drop.x,drop.y,room.state.zoneX,room.state.zoneY)).toBeLessThan(room.state.zoneRadius);expect(room.terrainKindAt(drop.x,drop.y)).not.toMatch(/water|building/);}});

  it('opens only once and creates one flamethrower with two fuel canisters',()=>{const room=smallRoom();room.lootRandom=createSeededRandom(2);const player=landedPlayer('opener',1700,1700);room.state.players.set(player.id,player);const drop=new SupplyDropState();drop.id='supply-flame';drop.x=player.x+20;drop.y=player.y;drop.landed=true;drop.specialWeapon='flamethrower';room.state.supplyDrops.set(drop.id,drop);expect(room.openNearbySupplyDrop(player)).toBe(true);const first=room.state.loot.size;expect(room.openNearbySupplyDrop(player)).toBe(false);expect(room.state.loot.size).toBe(first);const kinds=[...room.state.loot.values()].map((value:any)=>value.kind);expect(kinds.filter((kind:string)=>kind==='flamethrower')).toHaveLength(1);expect(kinds.filter((kind:string)=>kind==='fuel_ammo')).toHaveLength(2);});

  it('creates matching rocket ammunition when the supply chooses bazooka',()=>{const room=smallRoom();room.lootRandom=createSeededRandom(5);const drop=new SupplyDropState();drop.id='supply-bazooka';drop.x=1700;drop.y=1700;drop.landed=true;drop.specialWeapon='bazooka';room.spawnSupplyContents(drop);const kinds=[...room.state.loot.values()].map((value:any)=>value.kind);expect(kinds.filter((kind:string)=>kind==='bazooka')).toHaveLength(1);expect(kinds.filter((kind:string)=>kind==='rocket_ammo')).toHaveLength(2);expect(kinds).not.toContain('fuel_ammo');});

  it('creates matching rail slugs when the supply chooses railgun',()=>{const room=smallRoom();room.lootRandom=createSeededRandom(7);const drop=new SupplyDropState();drop.id='supply-railgun';drop.x=1700;drop.y=1700;drop.landed=true;drop.specialWeapon='railgun';room.spawnSupplyContents(drop);const kinds=[...room.state.loot.values()].map((value:any)=>value.kind);expect(kinds.filter((kind:string)=>kind==='railgun')).toHaveLength(1);expect(kinds.filter((kind:string)=>kind==='rail_slug')).toHaveLength(2);expect(kinds).not.toContain('rocket_ammo');});

  it('fires while riding, consumes fuel and damages players and motorcycles in front',()=>{const room=smallRoom();const player=landedPlayer('flamer',1800,1800);armFlamethrower(player);const front=landedPlayer('front',2000,1800);const back=landedPlayer('back',1600,1800);room.state.players.set(player.id,player);room.state.players.set(front.id,front);room.state.players.set(back.id,back);const ownBike=new MotorcycleState();ownBike.id='own-bike';ownBike.x=player.x;ownBike.y=player.y;ownBike.driverId=player.id;ownBike.velocityX=MOTORCYCLE_BALANCE.maxSpeedMultiplier*100;room.state.motorcycles.set(ownBike.id,ownBike);const targetBike=new MotorcycleState();targetBike.id='target-bike';targetBike.x=2020;targetBike.y=1830;targetBike.hp=180;room.state.motorcycles.set(targetBike.id,targetBike);player.isDriving=true;player.vehicleId=ownBike.id;room.firePlayer(player);expect(player.flamethrowerMagazine).toBe(99);expect(front.hp).toBe(100-FLAMETHROWER_BALANCE.playerDamagePerTick);expect(back.hp).toBe(100);expect(targetBike.hp).toBe(180-FLAMETHROWER_BALANCE.vehicleDamagePerTick);expect(ownBike.hp).toBe(180);expect(room.state.flameJets.size).toBe(1);});

  it('does not fire or create a visual jet with an empty tank and no reserve fuel',()=>{const room=smallRoom();const player=landedPlayer('empty',1800,1800);armFlamethrower(player,0);player.fuelAmmo=0;room.state.players.set(player.id,player);room.firePlayer(player);expect(player.flamethrowerMagazine).toBe(0);expect(room.state.flameJets.size).toBe(0);});

  it('caps multiple flamethrowers to one damage tick per target',()=>{const room=smallRoom();const first=landedPlayer('first',1700,1780),second=landedPlayer('second',1700,1820),target=landedPlayer('target',1930,1800);armFlamethrower(first);armFlamethrower(second);room.state.players.set(first.id,first);room.state.players.set(second.id,second);room.state.players.set(target.id,target);room.firePlayer(first);room.firePlayer(second);expect(target.hp).toBe(100-FLAMETHROWER_BALANCE.playerDamagePerTick);});

  it('blocks flame through solid collision geometry',()=>{const room=smallRoom();const rect=MAP_CONFIGS.small.bulletObstacles[0]!;const player=landedPlayer('wall-flamer',rect.x-80,rect.y+rect.h/2);armFlamethrower(player);const target=landedPlayer('wall-target',rect.x+rect.w+80,player.y);room.state.players.set(player.id,player);room.state.players.set(target.id,target);room.firePlayer(player);expect(target.hp).toBe(100);});

  it('preserves tank fuel and reserve through death inventory drops',()=>{const room=smallRoom();const player=landedPlayer('fuel-drop',1800,1800);player.phase='dead';player.primary='flamethrower';player.flamethrowerMagazine=37;player.fuelAmmo=125;room.dropInventory(player);const drops=[...room.state.loot.values()] as any[];expect(drops.find((value)=>value.kind==='flamethrower')?.weaponMagazine).toBe(37);expect(drops.find((value)=>value.kind==='fuel_ammo')?.ammoCount).toBe(125);expect(WEAPONS.flamethrower.range).toBe(FLAMETHROWER_BALANCE.range);});
});
